services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: photos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio

  api:
    build: ./api
    ports:
      - "8100:8000"
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: photos
      POSTGRES_HOST: postgres
      PHOTOS_PATH: /app/images
    volumes:
      - ./api:/app
      - /home/spak22/portfolio-app/images:/app/images:ro  # Update this path image folder
    depends_on:
      - postgres
    networks:
      - portfolio

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - portfolio

networks:
  portfolio:
    driver: bridge

volumes:
  postgres_data:
