version = 4.2.0
archive_dir = /etc/letsencrypt/archive/thisguyisreallycool.sp4k.live
cert = /etc/letsencrypt/live/thisguyisreallycool.sp4k.live/cert.pem
privkey = /etc/letsencrypt/live/thisguyisreallycool.sp4k.live/privkey.pem
chain = /etc/letsencrypt/live/thisguyisreallycool.sp4k.live/chain.pem
fullchain = /etc/letsencrypt/live/thisguyisreallycool.sp4k.live/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 5aaf1dd093992a1099122df5e9c80e60
rsa_key_size = 4096
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
thisguyisreallycool.sp4k.live = /var/www/certbot
