# Generated by Django 5.2.5 on 2025-08-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('photos_found', models.IntegerField(default=0)),
                ('photos_added', models.IntegerField(default=0)),
                ('photos_updated', models.IntegerField(default=0)),
                ('scan_duration', models.FloatField(help_text='Scan duration in seconds')),
                ('errors', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500, unique=True)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('camera_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lens_name', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_width', models.IntegerField(blank=True, null=True)),
                ('resolution_height', models.IntegerField(blank=True, null=True)),
                ('focal_length', models.FloatField(blank=True, help_text='Focal length in mm', null=True)),
                ('shutter_speed', models.CharField(blank=True, help_text="e.g., '1/250'", max_length=20, null=True)),
                ('aperture', models.CharField(blank=True, help_text="e.g., 'f/2.8'", max_length=10, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('date_captured', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('caption', models.TextField(blank=True, help_text='User-provided caption/description', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this photo is visible in public portfolio')),
                ('tags', models.ManyToManyField(blank=True, related_name='photos', to='photos.tag')),
            ],
            options={
                'ordering': ['-date_captured', '-date_added'],
                'indexes': [models.Index(fields=['date_captured'], name='photos_phot_date_ca_502f4f_idx'), models.Index(fields=['date_added'], name='photos_phot_date_ad_c215bb_idx'), models.Index(fields=['is_public'], name='photos_phot_is_publ_2d152c_idx'), models.Index(fields=['file_path'], name='photos_phot_file_pa_65a143_idx')],
            },
        ),
    ]
