# Generated by Django 5.2.5 on 2025-08-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_tag_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoscanlog',
            name='photos_removed',
            field=models.IntegerField(default=0),
        ),
    ]
