# Generated by Django 5.2.5 on 2025-08-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_add_photos_removed_to_scan_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='has_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_path',
            field=models.CharField(blank=True, help_text='Path to thumbnail image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
